FROM node:alpine
WORKDIR /opt/app

RUN apk add --update --no-cache ca-certificates \
    && rm -rf /var/cache/apk/* \
    && addgroup -S nodeuser \
    && adduser -D -S -h /opt/app -s /sbin/nologin -G nodeuser nodeuser

RUN chmod g+rwx /opt/app

COPY package.json .         \
     package-lock.json .    \
     tsconfig.json .        \
     ./dest ./               


RUN npm install --only=production           \
    && chown -R nodeuser:nodeuser /opt/app

EXPOSE  9105
RUN     addgroup nodeuser root
USER    nodeuser

CMD [ "npm", "run-script",  "start-docker" ]