---
kind: Service
apiVersion: v1
metadata:
  name: pubs-svc-service
spec:
  type: NodePort
  selector:
    app: pubs-svc
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30501

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubs-service-deployment
  labels:
    app: pubs-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubs-svc
  template:
    metadata:
      labels:
        app: pubs-svc
    spec:
      containers:
      - name: pubs-svc
        image: architecting-software/node-pubs-service:latest
        env:
          - name: NODE_ENV
            value: k8s
        imagePullPolicy: Never
        ports:
        - containerPort: 8080